import { RefreshCw } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import api from '../../api/axios'

const normalizeRows = (payload) => { const rows = payload?.data ?? payload; return Array.isArray(rows) ? rows : [] }

function Monitoring() {
  const [rows, setRows] = useState([])
  const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { setLoading(true); try { const res = await api.get('/monitoring'); setRows(normalizeRows(res.data)) } catch { setRows([]) } finally { setLoading(false) } }, [])
  useEffect(() => { queueMicrotask(() => load()) }, [load])
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-7 py-6"><div><span className="text-xs font-semibold uppercase tracking-widest text-indigo-600">Pemantauan langsung</span><h1 className="mt-2 text-2xl font-bold text-slate-900">Monitoring Kompetensi</h1><p className="mt-1 text-sm text-slate-500">Pantau perkembangan asesmen dan progres belajar seluruh OPD secara real-time.</p></div><button className="inline-flex items-center rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 shadow-sm transition hover:border-indigo-200 hover:bg-indigo-50 hover:text-indigo-700" onClick={load}><i className="bi bi-arrow-clockwise mr-2"></i>Refresh</button></div>{loading ? <div className="py-16 text-center text-sm text-slate-500">Memuat...</div> : rows.length === 0 ? <div className="py-16 text-center text-sm text-slate-500">Belum ada data progres.</div> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr>{['Peserta', 'Asesmen', 'Progress / Nilai', 'Status'].map((heading) => <th className="px-7 py-4 font-semibold" key={heading}>{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => { const completed = row.status === 'selesai'; const passed = row.lulus; const progress = completed ? 100 : 50; return <tr className="transition hover:bg-indigo-50/40" key={row.id}><td className="px-7 py-4"><div className="font-semibold text-slate-800">{row.user?.name ?? '-'}</div><div className="mt-0.5 text-xs text-slate-500">{row.user?.opd_name ?? 'OPD'}</div></td><td className="px-7 py-4 text-slate-600">{row.asesmen?.judul ?? '-'}</td><td className="min-w-60 px-7 py-4"><div className="mb-2 flex justify-between text-xs"><strong className="text-slate-700">{completed ? `Nilai: ${row.nilai}` : 'Sedang mengerjakan'}</strong><span className="text-slate-500">{progress}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${completed ? (passed ? 'bg-emerald-500' : 'bg-rose-500') : 'animate-pulse bg-indigo-500'}`} style={{ width: `${progress}%` }}></div></div></td><td className="px-7 py-4">{completed ? <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${passed ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{passed ? 'Lulus' : 'Tidak Lulus'}</span> : <span className="rounded-full bg-cyan-50 px-2.5 py-1 text-xs font-semibold text-cyan-700">Mengerjakan</span>}</td></tr> })}</tbody></table></div>}</section>
}

export default Monitoring
